language: php
sudo: false

branches:
  only:
    - master
    - develop
    - /^(bugfix|feature)\/.*$/
    - interop

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65
  - MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65
  - MAGENTO_VERSION="magento-ce-1.6.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65
  - MAGENTO_VERSION="magento-ce-1.7.0.2" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65
  - MAGENTO_VERSION="magento-ce-1.8.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65
  # Do not download sample data of 1.9 -> The file is too big
  - MAGENTO_VERSION="magento-ce-1.9.0.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=65
  - MAGENTO_VERSION="magento-ce-1.9.1.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=65
  - MAGENTO_VERSION="magento-mirror-1.9.2.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=65

matrix:
  fast_finish: true
  exclude:
    # Newer Magento versions uses newer PHP versions
    - php: 5.3
      env: MAGENTO_VERSION="magento-ce-1.9.0.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

    - php: 5.3
      env: MAGENTO_VERSION="magento-ce-1.9.1.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

    - php: 5.3
      env: MAGENTO_VERSION="magento-mirror-1.9.2.1" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

    # Old Magneto Versions are not officially supported to run with PHP 5.5
    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.4.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=65

    - php: 5.5
      env: MAGENTO_VERSION="magento-mirror-1.5.1.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66

    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-1.6.2.0" DB=mysql INSTALL_SAMPLE_DATA=yes COVERAGE=66

    - php: 5.5
      env: MAGENTO_VERSION="magento-ce-1.7.0.2" DB=mysql INSTALL_SAMPLE_DATA=no COVERAGE=66

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction --ignore-platform-reqs

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `magento_travis`;'
  - export N98_MAGERUN_TEST_MAGENTO_ROOT="./${MAGENTO_VERSION}"
  - bin/n98-magerun install --magentoVersionByName="${MAGENTO_VERSION}" --installationFolder="./${MAGENTO_VERSION}" --dbHost=127.0.0.1 --dbUser=root --dbPass='' --dbName="magento_travis" --installSampleData=${INSTALL_SAMPLE_DATA} --useDefaultConfigParams=yes --baseUrl="http://travis.magento.local/"

script:
  - vendor/bin/phpunit --debug --stop-on-error --stop-on-failure
  - php tests/check-coverage.php clover.xml ${COVERAGE}
